source 'https://rubygems.org'

ruby '2.1.3'

gem 'sinatra'
gem 'thin'
gem 'rerun'
gem 'dm-sqlite-adapter'
gem 'dm-core'
gem 'sqlite3'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'dm-migrations' 
gem 'haml'
gem 'pry'
gem 'better_errors'
